### ISSUE TITLE
add traffic analytics

### ISSUE THREAD

**Issue by nthngalone** [MtHorebSocialMedia/mhlc-web#23]

**Comment by MtHorebSocialMedia** [comment]
Look at writing traffic stats to Google sheets for now.  having a hard time finding a free option that's not cookie based.  Really don't want to deal with cookies with privacy laws and user acceptance requirements and whatnot.

https://medium.com/@sakkeerhussainp/google-sheet-as-your-database-for-node-js-backend-a79fc5a6edd9

**Comment by nthngalone** [comment]
analytics and audit code has been added - closing this issue.  There is a separate issue open (#74 ) for an SSL error on Digital Ocean.
